### ISSUE TITLE
Z shell: _lp_runtime_format returns stray periods and fractional days, hours, minutes, and seconds

### ISSUE THREAD

**Issue by Magotchi** [liquidprompt/liquidprompt#790] opened 2023-10-11 18:02 UTC
Shell: zsh 5.9

Operating system: Arch Linux - Linux <REDACTED> 6.5.6-arch2-1 #1 SMP PREEMPT_DYNAMIC Sat, 07 Oct 2023 08:14:55 +0000 x86_64 GNU/Linux

Liquid Prompt version: 2.1.2 or master (b0af1a5eff5da520fcb02842aea35caef7e890ad)

### Steps to Reproduce
1. Source Liquid Prompt in Z shell (Zsh) with default settings (no /etc/liquidpromptrc file).

2. Run `sleep 2.1`.

3. Run `sleep 61.1`.

### Expected Behavior
The runtime outputs for steps 2 and 3 above should be `2s` and `1m2s`, respectively.

### Current Behavior
The runtime outputs for steps 2 and 3 above are `2.s` and `1.0333333333333334m2.s`, respectively. Using Bash, sourcing the same version of Liquid Prompt, the behavior is as expected.

### Possible Solution
Use printf with `%d` in _lp_runtime_format. As a quick workaround, I put the following in my .zshrc after sourcing Liquid Prompt. Maybe it could be simplified:
```zsh
_lp_runtime_format() {
    (( LP_ENABLE_RUNTIME )) || return 2

    lp_runtime_format=
    if (( _LP_RUNTIME_SECONDS >= LP_RUNTIME_THRESHOLD )); then
        # display runtime seconds as days, hours, minutes, and seconds
        (( _LP_RUNTIME_SECONDS >= 86400 )) && lp_runtime_format=$(printf %d $((_LP_RUNTIME_SECONDS / 86400)))d
        (( _LP_RUNTIME_SECONDS >= 3600 )) && lp_runtime_format+=$(printf %d $((_LP_RUNTIME_SECONDS % 86400 / 3600)))h
        (( _LP_RUNTIME_SECONDS >= 60 )) && lp_runtime_format+=$(printf %d $((_LP_RUNTIME_SECONDS % 3600 / 60)))m
        lp_runtime_format+=$(printf %d $((_LP_RUNTIME_SECONDS % 60)))s
    else
        return 1
    fi
}
```

Additionally, and this is more of a feature request, maybe allowing users to specify the number of desired decimal places for the seconds is desirable.

**Comment by Rycieos** [comment] 2023-10-12 01:39
This took a bit to figure out.

Turns out Zsh does support floating point math (from https://zsh.sourceforge.io/Doc/Release/Arithmetic-Evaluation.html):
> floating point numbers can be declared with the `float` builtin;

Then from the `SECONDS` docs (from https://zsh.sourceforge.io/Doc/Release/Parameters.html):
> SECONDS \<S>
> 
> The number of seconds since shell invocation. If this parameter is assigned a value, then the value returned upon reference will be the value that was assigned plus the number of seconds since the assignment.
> 
> Unlike other special parameters, the type of the `SECONDS` parameter can be changed using the `typeset` command. The type may be changed only to one of the floating point types or back to integer. For example, `typeset -F SECONDS` causes the value to be reported as a floating point number. The value is available to microsecond accuracy, although the shell may show more or fewer digits depending on the use of `typeset`. See the documentation for the builtin typeset in [Shell Builtin Commands](https://zsh.sourceforge.io/Doc/Release/Shell-Builtin-Commands.html#Shell-Builtin-Commands) for more details.

That was what I needed to reproduce this. If `typeset -F SECONDS` is ran **before** loading `liquidprompt`, it seems the internal variables end up inheriting the float type from `SECONDS`.

If you run `declare -p | grep SECONDS`, you should see either `typeset -E SECONDS=...` or `typeset -F SECONDS=...`.

I think this is a valid Zsh configuration that we should support. The question is do we support the floating points, or always cast to int.

This will fix it:
```diff
diff --git a/liquidprompt b/liquidprompt
index c6edb68..078a2cb 100755
--- a/liquidprompt
+++ b/liquidprompt
@@ -4796,6 +4796,7 @@ prompt_on() {

         if (( LP_ENABLE_RUNTIME || LP_ENABLE_RUNTIME_BELL )); then
             _LP_RUNTIME_LAST_SECONDS=$SECONDS
+            declare -gi _LP_RUNTIME_SECONDS
             add-zsh-hook preexec __lp_runtime_before
         fi
         if (( LP_ENABLE_TITLE_COMMAND )); then
```

But if we wanted floating point display, it would be a bit more complicated. Thoughts?

**Comment by Magotchi** [comment] 2023-10-12 20:54
I would expect the most likely desired customization would be to have a configurable number of decimal places displayed for the seconds, but there may be people who also want something more exotic, like simply getting a decimal fraction of the biggest-involved unit, like:

- 58.23 seconds renders as "58.23s"
- 118.23 seconds renders as "1.97m"
- 7,128.23 seconds renders as "1.98h"
- 97,997.23 seconds renders as "1.13d"

**Comment by Rycieos** [comment] 2023-10-14 20:01
I agree, I think it makes sense to add that customization. But that feature is somewhat complicated, and I want to get a fix in as soon as possible. I'll merge in my fix and close this issue, and I created an enhancement issue for your suggestion (linked above) for tracking.

**Closed** 2023-10-14 20:08 UTC
Labels: bug, zsh, runtime
