### ISSUE TITLE
Installation instructions for Arch Linux incorrect

### ISSUE THREAD

**Issue by christian-heusel** [liquidprompt/liquidprompt#822] opened 2024-02-20 12:39 UTC
Currently the installation instructions for Arch Linux as mentioned in the documentation are not correct:
https://github.com/liquidprompt/liquidprompt/blob/94d672b62e187f1ed332929c37c425246e7f1a09/docs/install/packages.rst?plain=1#L21-L30

### Expected Behavior
Installation instructions for Arch Linux work on a somewhat default install of Arch Linux.

### Current Behavior
The liquidprompt package is in the AUR and therefore not installable via pacman without being built before.

### Possible Solution
- The Wiki article on how to install & upgrade packages could be linked (https://wiki.archlinux.org/title/Arch_User_Repository#Installing_and_upgrading_packages)
- Directly mention the needed commands:
  ```
  $ git clone https://aur.archlinux.org/liquidprompt.git
  $ cd liquidprompt
  $ makepkg -si
  ```

I could also imagine some combination of the above i.e. with the commands and "for more details refer to ..." guiding to the wikipage.

**Comment by Rycieos** [comment] 2024-02-20 15:09
This should be fixed. I find it hard to believe that a package manager can't install a package from the AUR with one command. So either the package is broken, we have the wrong `pacman` command listed in the docs, or my expectations are too high.

I know @milouse was active in the package thread, but I have never interacted with the package maintainer, xuanruiqi, and am not sure how to get a hold of them. Hopefully we won't need to bug them, and someone who understands Arch better than I can clue us in to the cause.

**Comment by christian-heusel** [comment] 2024-02-20 15:56
> I find it hard to believe that a package manager can't install a package from the AUR with one command

Well the AUR is not a package repo in the literal meaning of the word as it does not contain packages but rather `PKGBUILD`s that can be used to build a package. There are various [aur helpers](https://wiki.archlinux.org/title/AUR_helpers) of which some wrap pacman to make it seem like a repo but it is not.

Also some Arch Linux derivatives include the chaotic aur project by default (i.e. garuda AFAIK) which pre-builds the packages and serves them as a repo which might also be a reason for this confusion.


So as I already said in the initial issue text, I think it would be good to just list the following commands instead of `pacman -S`:
```diff
-    pacman -S liquidprompt
+    $ git clone https://aur.archlinux.org/liquidprompt.git
+    $ cd liquidprompt
+    $ makepkg -si
```

> Hopefully we won't need to bug them, and someone who understands Arch better than I can clue us in to the cause

I think I can help out with that, no need to bug the maintainer 😄 I actually opened this thread because someone in the Arch IRC channels was confused how all of this can work 😆

**Comment by Rycieos** [comment] 2024-02-20 16:21
Fair enough. That just seems needlessly cumbersome. Homebrew works the same way (text file "formulas" that detail how to build and install a package), but it manages to wrap and present it in a way that looks like a more normal package manager. I don't see how Arch can compete with Debian or Enterprise Linux with such painful package management.

Anyway, nothing we can do to fix that. If that is truly the case, and your suggested docs change is the best way to install it, then I can update the docs. But it just seems so terrible; I find it very hard to believe that there is not a better way to install an AUR package.

**Comment by milouse** [comment] 2024-02-21 09:40
I think there are some misunderstanding about the packaging model of Archlinux. Here are some quick clarification to understand why you have to build AUR "packages" yourself.

As a lot of other linux distributions, Archlinux exposes a set of trusted / verified official repository. Only those repository are by default available through pacman, the official package manager. As of today, they are `core`, `extra`, `multilib` and their respective `testing` counterpart. All packages in those repositories have been carefully reviewed and prebuilt by a small team of "trusted" packager. Archlinux only supports those packages. Nothing else. If you need a comparison with the debian world, you can think of the the `main`, `contrib` and `non-free` branches of official repositories.

Now, if you really now what you are doing, and if you trust them, you can also add supplementary repositories in the pacman configuration. There are a lot out there, providing prebuilt packages for various subject. I [maintain one](https://archlinux.umaneti.net) myself, including a prebuilt version of liquidprompt. When adding such repository in your pacman config, you are the only responsible of what you do, and no one of the packages you may install from this repository is supported by Archlinux. You can be completely spoofed by an attacker and directly install a virus, trojan or other doing so. The custom repository feature might be seen as a handy way to distribute packages built by you between your various machine, or internal packages for a company… Again, if you need a comparison, you can think of the various ubuntu `ppa` repositories there. Each time you add a new one to your config, you are supposed to ensure you trust the provider.

Finally, there is the Archlinux User Repository (AUR), which is not a prebuilt repository **on purpose**. The main purpose of AUR is to let Archlinux users share packages recipes between them to easily install anything from the wild on their machine and still get some kind of new release notification. AUR is no more than a simple custom-Make-forum-exchange. It is NOT a package repository in the common sense of the term. The idea behind the "forced" compilation step, is to enforce end-user will really review the package recipe before trying to install it. There are absolutely NO control over AUR (apart *a posteriori* kind of moderation). Anyone can push anything there without any control or verification. If no one review the recipe, again, it can contain virus, trojan or anything else. AUR is really really for advanced users who really knows and understands what happen when they build the recipe they just downloaded.

Said otherwise, saying that the Archlinux package model is flawed compared to other distributions is wrong. AUR is actually NOT included in the "package model" of archlinux. That’s just an exchange forum. If you stick with default repositories, Archlinux behaves exactly the same as the other distributions: if a package is not available, you have to get your hand dirty and do the compilation yourself. Nothing new here.

In conclusion:

- AUR is widly misunderstood in the archlinux communities, and the fact a such prominent link is visible in the main menu of the official archlinux website does not help. But again, my best advice for anyone new to Archlinux or Arch derivative: do never trust anything from AUR and proceed with anything from AUR very carefully and manually. You will never run blindly a command from stackoverflow, thus do the same here. The [red warning in the Wiki](https://wiki.archlinux.org/title/Arch_User_Repository) say the same, but I agree no-one read wikis nowadays…
- So yes the command in the documentation is wrong and confusing. Until we convince an Archlinux Trusted Packager to include officially liquidprompt into the `extra` repository, it will not be possible to directly install it through `pacman`. The proposed fix is right, and *normally* every Archlinux user should be used to that (i.e. no reason to be more precise, like adding the required first steps of installing git, makepkg…). Another less involving fix would be to just say "liquidprompt is in AUR" with a link to the recipe, without giving any details and let the end-user install it through their preferred way (manually, AUR wrapper…)

I hope you have a clear view on the current situation :)

**Comment by milouse** [comment] 2024-02-21 09:48
Sorry it was a long and verbose message.

Now the solution: I’ve no problem pushing a MR to fix this part of the documentation.

@Rycieos what do you prefer?

1. exposing the correct commands to actually build the package from AUR (as proposed by @christian-heusel)
2. just letting the end-user know about the availability in AUR with a link to the recipe?

As a general notice, I also see that the documentation does not enforce that all those packages are made by third parties. Maybe we could had a little word saying liquidprompt does not support those packages?

**Comment by Rycieos** [comment] 2024-02-21 19:53
Thanks @tidalvirus and @milouse; that information is very helpful. Clearly my understanding of Arch and the AUR was lacking, and whoever wrote that installation documentation obviously didn't know what they were doing (me, it was me).

I have no strong opinion between options 1 and 2. I like complete documentation, but also it is Arch, and I would expect most users to know how to handle such things.

I think a note in the install docs that the OS repo packages are 3rd party is a great idea.

**Comment by milouse** [comment] 2024-02-23 11:05
I just pushed a proposal fixed. Let me know if it please you.

**Comment by Rycieos** [comment] 2024-02-24 17:17
Thanks to @milouse for updating the docs on this!

**Closed** 2024-02-24 17:16 UTC
Labels: bug
